// =======================================================
//   LEVEL DATA - The single source of truth for all maps.
// =======================================================

const TILE_SIZE = 40;

const LEVEL_1_MAP = [ "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                         E  ", "                                                      PPPPPP", "                                    P                         ", "                                   P P                        ", "                        PP        P   P                       ", "                       P H P      PPPP                        ", "                      P  H  P                                 ", "                      PPPPPPP        P    H H H    P          ", "                                     PPPPPPPPP                ", "           P                                                  ", "          P P                                                 ", "  S      P   P        P H P                                   ", " PPPPP   PPPPPP       PPPPPPP            PPPP                  ", " P   P                                HHH                     ", " P   P   PPPP                                                 ", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP" ];
const LEVEL_2_MAP = LEVEL_1_MAP.map(row => row.split('').reverse().join('').replace('S','_TEMP_').replace('E','S').replace('_TEMP_','E'));
const LEVEL_3_MAP = [ "                                                           E", "                                                        PPPP", "                                                            ", "                                             P H P          ", "                                           PPPPPPP          ", "                                  P H P                     ", "                                PPPPPPP                     ", "                       P H P                                ", "                     PPPPPPP                                ", "                                                            ", "                    P                                       ", "                   P                                        ", "            H H H P                                         ", "           PPPPPP P                                         ", "                  P                                         ", "   S             P                                          ", "PPPPPPPPPPPPPPPPPP                                          ", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP" ];
const LEVEL_4_MAP = [ "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                        B      P    P                    E   ", " S      P             PPPP   PPPPPP   PPPPPPPPPPPPPPPPPPPPPPPP", " PPPPPPPP                                                     ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            " ];
const LEVEL_5_MAP = [ "                                                            ", "                                                            ", "                                                         E  ", "                                                      PPPPPP", "                                                            ", "                                                            ", "                                                            ", "                                       B                    ", "                                    PPPPPP                  ", "                                                            ", "                             B                              ", "                          PPPPPP                            ", "                                                            ", "                   B                                        ", " S              PPPPPP                                      ", " PPPPPPPPPPP                                                  ", "                                                            ", "                                                            " ];
const LEVEL_6_MAP = [ "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                               PPPPPPPPP                    ", "                               P                            ", "                               P                            ", "                               P H H H H H H H H H H H H H E", "                               PPPPPPPPPPPPPPPPPPPPPPPPPPPPP", "  S      B                     P                            ", "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP                            " ];
const LEVEL_7_MAP = [ "                                                            ", "                                                            ", "                     P      E      P                        ", "                     P PPPPPPPPPP P                        ", "                     P P          P                        ", "                     P P B        P                        ", "                     P PPPPPPPPPPPP                        ", "                     P                                     ", "                     P                                     ", " S                   P                                     ", "PPPPPPPPPPPPPPPPPPPPPP                                     " ];

// --- UPDATED Level 8: "The Dash Gap" ---
const LEVEL_8_MAP = [
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    "                                                            ",
    " S                                                E         ",
    "PPPPPPPPP                    PPPPPPPPP                      ",
    "                                                            ",
];

const LEVEL_9_MAP = [ "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                       B                 E  ", "                                    PPPPPP        PPPPPPPPPP", "                                                            ", "                                                            ", " S                                                          ", "PPPPPPP                                                     ", "                                                            " ];
const LEVEL_10_MAP = [ "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                                                            ", "                          PPPPPPPPP                      E  ", "                         P         P                  PPPPPP", "                         P H H H H P                        ", "                         P         P                        ", "                 B       P         P                        ", " S        PPPPPPPPPPPPPPPP         PPPPPP                   ", "PPPPPP                                                      ", "                                                            " ];

// The main array that the game will use.
const LEVEL_MAPS = [ LEVEL_1_MAP, LEVEL_2_MAP, LEVEL_3_MAP, LEVEL_4_MAP, LEVEL_5_MAP, LEVEL_6_MAP, LEVEL_7_MAP, LEVEL_8_MAP, LEVEL_9_MAP, LEVEL_10_MAP ];